### ISSUE TITLE
Doesn't support Unix Sockets with colons in them.

### ISSUE THREAD

**Issue by centerorbit** [zgoat/zdb#2]
I believe I've pinned my connection issues with goatcounter down to this.

When you attach Google Cloud SQL (of the postgres variety) to a container/instance you can access it locally via a Linux socket in the `/cloudsql/` directory of that instance.

Unfortunately the socket connection name contains colons ':' for example: website-328316:us-central1:goatcounter.

When trying to connect to this via the following connection string:
`postgresql://dbname=goatcounter user=postgres password=<PASSWORD> hostaddr=/cloudsql/website-328316:us-central1:goatcounter`

You recieve a rather cryptic error:
```
goatcounter: zdb.Connect: connectPostgreSQL: parse "postgresql://dbname=goatcounter user=postgres password=<PASSWORD> hostaddr=/cloudsql/website-328316:us-central1:goatcounter": invalid character " " in host name
```

The work-around (which I haven't tested yet) is to not use the built-in SQL connector and instead configure a static IP and allow-list that IP address on your SQL instance and then provision ssl connection certs.

**Comment by arp242** [comment]
I set this in my postgresql.conf:

    % unix_socket_directories = '/tmp/a:b'

And then I can connect with:

    % psql -h /tmp/a:b

And then goatcounter indeed fails, although with a different error message than what you have:

    % goatcounter serve -db 'postgresql://dbname=goatcounter hostaddr=/tmp/a:b'
    goatcounter: zdb.Connect: connectPostgreSQL: dial tcp: lookup hostaddr=: no such host

But using `host=` instead of `hostaddr=` seems to work:

    % goatcounter serve -db 'postgresql://dbname=goatcounter host=/tmp/a:b'

And everything works.

Looking at the pq library it uses to connect to PostgreSQL, it looks like [it doesn't support hostaddr at all](https://github.com/lib/pq/issues/860), and the only reference I can find in the code base is [this](https://github.com/lib/pq/blob/master/conn.go#L1997-L1998), which confirms it's unsupported. So it falls back to the default values (possibly from the environment with `PG*` variables), which explains why we get different messages.

I also set `unix_socket_directories` to `/cloudsql/website-328316:us-central1:goatcounter` and created that directory, to make sure there isn't another problem, and this path works for me too:

    % goatcounter serve -db 'postgresql://dbname=goatcounter host=/cloudsql/website-328316:us-central1:goatcounter'

So I think the solution is to `s/hostaddr/host` and it should be good(?) I can't test this on your environment though.

**Comment by arp242** [comment]
One of the messy things about connecting to PostgreSQL is that there are two "styles" or connection strings:

    dbname=mydb host=myhost

And:

    postgres://myhost/mydb  # Can also be postgresql://

But in zdb we use `dbname://` to select the database engine (i.e. `sqlite://..`. or `mariadb://...`), so we don't really have a good way to detect if we use "URL-style" connection string, so we try both, but this often leads to confusing error messages, as you always get the error from trying to connect with the "URL-style".

I regret doing it like this; it's done like this because a single user reported being confused about this in the very early days of GoatCounter. I should just tell people to use `postgres://postgress://myhost/mydb`, perhaps allowing for a shortcut like `postgre://:myhost/mydb`, which is a bit ugly but a lot clearer. Then again, you will get people being confused why just `postgress://myhost/mydb` doesn't work :-/ So yeah, I don't know – every time I look at this I think "darn, I should really change this!" and then I can never really figure out *what* to change it to.

**Comment by centerorbit** [comment]
OMG changing `hostaddr` to `host` fixed the issue! :sob: :sob: . I have at least 20 different pipeline deploys over 2 days to reach this solution!

Thank you!! :raised_hands: 

In the next few days I'll make a PR to goatcounter to add this information to the DB documentation README.

**Comment by arp242** [comment]
> In the next few days I'll make a PR to goatcounter to add this information to the DB documentation README.

I want to change the PostgreSQL driver from "pg" to "pgx"; the pg one has been in "bug-fix only" maintenance mode for quite a while, but even bugfixes are slow to trickle in. This should solve this, and also some other issues/workarounds. I looked a bit at it today, and it's fairly clear what needs to be done (I think...), just need to do it.

So basically, it shouldn't be needed to make a PR; I just need to update/fix this.

Then I can finally properly release this library which has been "90% finished" for ages 🙃

**Comment by centerorbit** [comment]
Huh, the first deploy worked and so far I've tried two more and they are failing in the same way:

```
 zdb.Connect: connectPostgreSQL: parse "postgresql://dbname=goatcounter user=postgres password=<PASSWORD> host=/cloudsql/website-328316:us-central1:goatcounter": invalid character " " in host name
```

With a connection string of:
```
postgresql://dbname=goatcounter user=postgres password=<PASSWORD> host=/cloudsql/website-328316:us-central1:goatcounter
```

Is there a chance that I'm hitting a race condition? I'll try deploying a few more to see what happens and maybe gather more details. It doesn't make sense to me why one worked and two failed so I suspect something amiss on my end.

**Comment by arp242** [comment]
You're probably running in to some other error and the error is misleading because of the issue I mentioned before: it tries both connection string styles, and reports only the last error (for the "URL style"). Try using a URL instead of the key/value connection string. That should at least give the correct error.

**Comment by centerorbit** [comment]
The URL style is working much better now. Here is what I'm using:
```
CONNECTION_STRING="postgresql:///goatcounter?user=postgres&password=$PASSWORD&host=/cloudsql/$INSTANCE_CONNECTION_NAME"
goatcounter serve -automigrate -tls http -listen ":$PORT"  -public-port "$PORT" -db "$CONNECTION_STRING"
```

I don't know if this helped, but I added an additional slash after the ://

Also I had to make sure that the unix socket 'host=' parameter was the last option, because otherwise it'd think that user= or password= was part of the socket name.

Thank you Martin for your help!

(This issue led me to trying the /// and the parameter layout: https://github.com/golang-migrate/migrate/issues/211)

**Comment by arp242** [comment]
I changed now changed it to "engine+connect string"; so in the next release you'll use:

    -db "postgresql+/goatcounter?user=postgres&password=$PASSWORD&host=/cloudsql/$INSTANCE""

It kind of sucks that it's incompatible, but it's a fairly trivial change and should be much better and reduce confusion. I chose `+` specifically so it won't conflict with connection strings starting with a `/` (as in this example) or `:` (e.g. `:memory:` in SQLite).

The other issue is really a pq problem, so not much that can be done about it here as such.

**Comment by centerorbit** [comment]
Thanks Martin!

Will this be in a v3.x.x release? (I've set this up on a v2.1.0 tag)

**Comment by arp242** [comment]
I think I'll just release it as v2.2.0; as dealing with /v3 Go import paths is annoying. I regret doing v2. I'll have to look, but can probably just do a string replace on `://` and issue a warning, so it doesn't necessarily need to break things.
